### PR TITLE
run tests on travis 

### PR DESCRIPTION
**Pull request by mathieujobin**

### CODE REVIEW

**Comment by notEthan** [comment]
I think I prefer not to do coveralls on this. travis is probably a good thing to add though.

**Comment by notEthan** [comment]
travis bump

**Comment by mathieujobin** [comment]
all tests passed

**Comment by mathieujobin** [comment]
i just noticed your comment @notEthan 
removed coveralls

**Comment by notEthan** [comment]
cool, thanks

**Pull request merged**
